# Generated by Django 5.1.2 on 2024-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=290, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('encrypted_password', models.CharField(max_length=120)),
            ],
        ),
    ]
