# Generated by Django 5.1.3 on 2024-11-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idearest25app', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest25app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest25app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest25app.customuser')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idearest25app.idea')),
            ],
        ),
    ]
